name: Publish Daily

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 0:00
  workflow_dispatch: # or manually
    
jobs:
  publish_amd64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install snapcraft
      run: |
        sudo snap install snapcraft --classic
        snapcraft login
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
    - name: build & publish snap
      run: |
        sudo snapcraft --destructive-mode
        sudo snapcraft upload --release=edge freecad*.snap
