name: Publish Daily

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 0:00
  workflow_dispatch: # or manually
    
jobs:
  publish_amd64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install snapcraft
      run: sudo snap install snapcraft --classic
    - name: build snap
      id: build
      run: |
        sudo -H snapcraft --enable-experimental-extensions --destructive-mode
        snap=$(ls freecad*.snap)
        echo "::set-output name=snap::$snap"
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: edge
